services:
  login-register-database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Contraseña para el usuario root
    volumes:
      - db_data_prod:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend-production

volumes:
  db_data_prod:

networks:
  backend-production:  # Definición de la red