spring:
  application:
    name: ecommerce-management-API
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false
#logging:
#  level:
#    org.springframework: DEBUG
