#comment
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: ecommerce-management-API
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
logging:
  level:
    root: INFO
    com.app.ecommerce_management_api: DEBUG
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /index.html
  packages-to-scan: com.app.ecommerce_management_api
---
#spring:
#  config:
#    activate:
#      on-profile: prod
#  application:
#    name: ecommerce-management-API
#  datasource:
#    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#    open-in-view: false
#logging:
#  level:
#    root: WARN
#    com.app.ecommerce_management_api: INFO
#springdoc:
#  api-docs:
#    enabled: true
#    path: /v3/api-docs
#  swagger-ui:
#    enabled: true
#    path: /index.html
#  packages-to-scan: com.app.ecommerce_management_api

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: ecommerce-management-API
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
logging:
  level:
    root: INFO
    com.app.ecommerce_management_api: DEBUG
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /index.html
  packages-to-scan: com.app.ecommerce_management_api